---
name: ci

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  dist-zip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Distribution Zip
        run: make dist
      - name: Pub
        uses: actions/upload-artifact@v2
        with:
          name: ghidra-native-0.2.0.zip
          path: ghidra-native-0.2.0.zip
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Patching
        run: make patch
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Patching
        run: make patch
#  build-windows:
#    runs-on: windows-latest
#    steps:
#    - uses: actions/checkout@v2
#    - name: Windows Dependencies
#      run: pip install meson ninja
#    - name: Building Sdb
#      run: meson build && ninja -C build
#    - name: Pub
#      uses: actions/upload-artifact@v2
#      with:
#        path: build/*.exe
